import type { AgentMessage, ContentBlock } from "../model-router/types";

/**
 * Issue #61(c) — stale-snapshot elision. The agent always acts on the
 * CURRENT page; historical DOM snapshots are dead weight in context. This
 * pure, deterministic transform runs in the wire-time pipeline (on the
 * windowed COPY only — at-rest agentMessages stay RAW per R28 v2) and
 * replaces the bulky part of every stale page snapshot with a short marker,
 * keeping the cheap semantic header (url / title / headings / frame_map).
 *
 * Two carriers of snapshot bulk are elided:
 *   - the observation TEXT block (legacy push-mode shape: header + frames) —
 *     only the LAST text block of each stale user turn is treated as the
 *     observation;
 *   - tool_result blocks whose content is a read_page snapshot (pull mode:
 *     `Current URL / Page title / <frame_map>` header, then a potentially
 *     huge `<interactive_index>` + `<untrusted_page_content>` payload).
 *     Eliding these keeps the react segment slim so the sliding window /
 *     compaction almost never need to cut — which is what keeps the
 *     provider prefix cache hot on long page-operation tasks. The
 *     tool_use_id pairing is untouched (Anthropic only requires the block
 *     to exist with a matching id; its content is free-form).
 *
 * Non-snapshot tool results (read_struct / search_web / editor content …)
 * carry data the task may aggregate later and are never elided.
 *
 * The transform is monotone: a block elided at step N stays elided
 * byte-identically at every later step (only the previous last user turn
 * flips full → marker once, near the tail), so the wire prefix grows
 * append-only and auto-prefix caches (OpenAI / Moonshot / DeepSeek) keep
 * hitting across steps.
 */

/** Marker that replaces an elided snapshot's bulky part. */
export const STALE_OBSERVATION_MARKER =
  "[This earlier page snapshot's interactive index and page content were omitted to save context. " +
  "Only the most recent snapshot is shown in full. If you still need details from this " +
  "page, re-read it (e.g. read_page) or rely on notes you kept in your reasoning.]";

/**
 * Literals that begin the bulky part of a page snapshot, in whichever order
 * they appear. The FIRST occurrence of any of them is the cut point —
 * everything before it is the cheap header, everything from it on can be
 * regenerated by re-reading the page.
 *   - `<interactive_index` — read-page.ts renders the element index (up to
 *     300 <interactive_element> lines) BEFORE the frame content blocks.
 *   - `<untrusted_page_content` — per-frame block emitted by read-page.ts
 *     (atlas / content / full payloads).
 */
const BULK_MARKERS = ["<interactive_index", "<untrusted_page_content"];

function elideText(text: string): string | null {
  let cut = -1;
  for (const marker of BULK_MARKERS) {
    const idx = text.indexOf(marker);
    if (idx !== -1 && (cut === -1 || idx < cut)) cut = idx;
  }
  if (cut === -1) return null; // no snapshot bulk; leave as-is
  const header = text.slice(0, cut).trimEnd();
  return header ? `${header}\n\n${STALE_OBSERVATION_MARKER}` : STALE_OBSERVATION_MARKER;
}

export function elideStaleObservations(messages: AgentMessage[]): AgentMessage[] {
  // The most-recent user turn carries the current observation — never elide it.
  let lastUserIdx = -1;
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === "user") {
      lastUserIdx = i;
      break;
    }
  }

  return messages.map((msg, idx) => {
    if (idx === lastUserIdx) return msg;
    if (msg.role !== "user") return msg;
    if (typeof msg.content === "string") return msg;
    const blocks = msg.content as ContentBlock[];

    // Lazily-cloned output; a message with nothing to elide keeps its identity.
    let newBlocks: ContentBlock[] | null = null;
    const replaceBlock = (i: number, block: ContentBlock) => {
      if (!newBlocks) newBlocks = blocks.slice();
      newBlocks[i] = block;
    };

    // The observation is the LAST text block in the user turn.
    for (let i = blocks.length - 1; i >= 0; i--) {
      if (blocks[i].type === "text") {
        const textBlock = blocks[i] as Extract<ContentBlock, { type: "text" }>;
        const elided = elideText(textBlock.text);
        if (elided !== null) replaceBlock(i, { type: "text", text: elided });
        break;
      }
    }

    // Stale read_page snapshots ride tool_result blocks (pull mode). Replace
    // their bulky payload with the marker, preserving toolUseId pairing.
    for (let i = 0; i < blocks.length; i++) {
      const block = blocks[i];
      if (block.type !== "tool_result") continue;
      const elided = elideText(block.content);
      if (elided !== null) replaceBlock(i, { ...block, content: elided });
    }

    return newBlocks ? { ...msg, content: newBlocks } : msg;
  });
}
