import type { AgentMessage, ContentBlock } from "../model-router/types";

/**
 * Issue #61(c) — stale-snapshot elision. The agent always acts on the
 * CURRENT page; historical DOM snapshots are dead weight in context. This
 * pure, deterministic transform runs in the wire-time pipeline (on the
 * windowed COPY only — at-rest agentMessages stay RAW per R28 v2) and
 * replaces the bulky part of every stale page snapshot with a short marker,
 * keeping the cheap semantic header (url / title / headings / frame_map).
 *
 * Two carriers of snapshot bulk are elided:
 *   - the observation TEXT block (legacy push-mode shape: header + frames) —
 *     only the LAST text block of each stale user turn is treated as the
 *     observation;
 *   - tool_result blocks whose content is a read_page snapshot (pull mode:
 *     `Current URL / Page title / <frame_map>` header, then a potentially
 *     huge `<interactive_index>` + `<untrusted_page_content>` payload).
 *     Eliding these keeps the react segment slim so the sliding window /
 *     compaction almost never need to cut — which is what keeps the
 *     provider prefix cache hot on long page-operation tasks. The
 *     tool_use_id pairing is untouched (Anthropic only requires the block
 *     to exist with a matching id; its content is free-form).
 *
 * Non-snapshot tool results (read_struct / search_web / editor content …)
 * carry data the task may aggregate later and are never elided — see
 * isTargetEvidenceTag for how the target tools are told apart despite sharing
 * read_page's wrapper tag.
 *
 * The transform is monotone: a block elided at step N stays elided
 * byte-identically at every later step (only the previous last user turn
 * flips full → marker once, near the tail), so the wire prefix grows
 * append-only and auto-prefix caches (OpenAI / Moonshot / DeepSeek) keep
 * hitting across steps.
 */

/** Marker that replaces an elided snapshot's bulky part. */
export const STALE_OBSERVATION_MARKER =
  "[This earlier page snapshot's interactive index and page content were omitted to save context. " +
  "Only the most recent snapshot is shown in full. If you still need details from this " +
  "page, re-read it (e.g. read_page) or rely on notes you kept in your reasoning.]";

/**
 * Literals that begin the bulky part of a page snapshot, in whichever order
 * they appear. The FIRST occurrence of any of them is the cut point —
 * everything before it is the cheap header, everything from it on can be
 * regenerated by re-reading the page.
 *   - `<interactive_index` — read-page.ts renders the element index (up to
 *     300 <interactive_element> lines) BEFORE the frame content blocks.
 *   - `<untrusted_page_content` — per-frame block emitted by read-page.ts
 *     (atlas / content / full payloads).
 */
const BULK_MARKERS = ["<interactive_index", "<untrusted_page_content"];

/**
 * Is this `<untrusted_page_content …>` opening tag carrying TARGET EVIDENCE
 * rather than a page snapshot?
 *
 * `read_struct` / `read_target` / `find_target` reuse the same wrapper tag as
 * read_page (target-tools.ts), but what they return is extracted task evidence
 * — the rows the task is aggregating, the target_id it locked onto. That is
 * worth MORE across turns than a page snapshot, not less: a snapshot can be
 * re-read from the live page, an extracted record cannot (the page may have
 * paginated away). Eliding them silently destroyed exactly the data the task
 * was collecting.
 *
 * Detected by the `target_id` attribute rather than the tag name: the tag list
 * is duplicated verbatim across five files under a parity test, and a new tag
 * would have to be threaded through all of them for no semantic gain. Failure
 * mode is safe either way — an unrecognised tag simply is not elided.
 */
function isTargetEvidenceTag(text: string, tagStart: number): boolean {
  const tagEnd = text.indexOf(">", tagStart);
  if (tagEnd === -1) return false;
  return text.slice(tagStart, tagEnd).includes("target_id=");
}

function elideText(text: string): string | null {
  let cut = -1;
  for (const marker of BULK_MARKERS) {
    let idx = text.indexOf(marker);
    while (idx !== -1 && isTargetEvidenceTag(text, idx)) {
      idx = text.indexOf(marker, idx + 1);
    }
    if (idx !== -1 && (cut === -1 || idx < cut)) cut = idx;
  }
  if (cut === -1) return null; // no snapshot bulk; leave as-is
  const header = text.slice(0, cut).trimEnd();
  return header ? `${header}\n\n${STALE_OBSERVATION_MARKER}` : STALE_OBSERVATION_MARKER;
}

/**
 * @param keepLatest  Keep the most-recent user turn's snapshot in full (the
 *   wire-time default — that turn is the page the agent is acting on). Pass
 *   false when the messages are headed for the compaction summarizer instead
 *   of the wire: there every snapshot is about to be replaced by a summary,
 *   and the summarizer is explicitly told to omit DOM listings, so shipping
 *   the raw payload is pure waste.
 */
export function elideStaleObservations(
  messages: AgentMessage[],
  keepLatest: boolean = true,
): AgentMessage[] {
  // The most-recent user turn carries the current observation — never elide it.
  let lastUserIdx = -1;
  if (keepLatest) {
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "user") {
        lastUserIdx = i;
        break;
      }
    }
  }

  return messages.map((msg, idx) => {
    if (idx === lastUserIdx) return msg;
    if (msg.role !== "user") return msg;
    if (typeof msg.content === "string") return msg;
    const blocks = msg.content as ContentBlock[];

    // Lazily-cloned output; a message with nothing to elide keeps its identity.
    let newBlocks: ContentBlock[] | null = null;
    const replaceBlock = (i: number, block: ContentBlock) => {
      if (!newBlocks) newBlocks = blocks.slice();
      newBlocks[i] = block;
    };

    // The observation is the LAST text block in the user turn.
    for (let i = blocks.length - 1; i >= 0; i--) {
      if (blocks[i].type === "text") {
        const textBlock = blocks[i] as Extract<ContentBlock, { type: "text" }>;
        const elided = elideText(textBlock.text);
        if (elided !== null) replaceBlock(i, { type: "text", text: elided });
        break;
      }
    }

    // Stale read_page snapshots ride tool_result blocks (pull mode). Replace
    // their bulky payload with the marker, preserving toolUseId pairing.
    for (let i = 0; i < blocks.length; i++) {
      const block = blocks[i];
      if (block.type !== "tool_result") continue;
      const elided = elideText(block.content);
      if (elided !== null) replaceBlock(i, { ...block, content: elided });
    }

    return newBlocks ? { ...msg, content: newBlocks } : msg;
  });
}
